FROM apache/airflow:2.8.1

USER root

# Install OpenJDK for PySpark
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       default-jre-headless \
       procps \
    && apt-get autoremove -yqq --purge \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow

# Install PySpark so Airflow can run spark-submit
RUN pip install --no-cache-dir pyspark==3.5.1
